version: '3.3'
services:
  satellite_simulator:
      build: .
      networks:
        - project-network
      ports:
        - "5000:5000"
      restart: always
      environment:
        BUCKET_NAME: ""
        AWS_ACCESS_KEY_ID: ""
        AWS_SECRET_ACCESS_KEY: ""
        AWS_DEFAULT_REGION: ""
networks:
  project-network:
    driver: bridge